data_processing:
  feature_cols:
  - speed
  - mileage
  - total_volt
  - total_current
  - max_cell_volt
  - min_cell_volt
  - max_temp
  - min_temp
  - temperature_c
  - relative_humidity
  - visibility_km
  - wind_speed_ms
  input_file: aligned_data_refined_soc.csv
  label_col: refined_soc
  max_time_gap: 500
  sequence_length: 40
  split:
    test: 0.15
    validation: 0.15
  stride: 20
  time_col: DATE
experiment_name: lstm_400s
model:
  dropout: 0.1
  hidden_size: 128
  input_size: null
  num_layers: 3
  output_size: 1
paths:
  csv_save_name: lstm_400s_predictions_detail.csv
  log_dir: logs
  model_save_name: best_lstm_400s_model.pth
  plot_save_name: lstm_400s_prediction_scatter.png
  processed_data_file: lstm_400s_data.npz
  processed_scaler_file: lstm_400s_scalers.pkl
training:
  batch_size: 32
  epochs: 108
  learning_rate: 0.0001
  loss_function: mae
  optimizer: adam
  patience: 30
  scheduler:
    factor: 0.5
    patience: 5
    type: ReduceLROnPlateau
