# configs/config_200s.yaml

experiment_name: "lstm_200"

data_processing:
  input_file: "aligned_data_refined_soc.csv"

  sequence_length: 20
  stride: 10
  max_time_gap: 3600


  time_col: "DATE"
  label_col: "refined_soc"

  feature_cols:
    - "speed"
    - "mileage"
    - "total_volt"
    - "total_current"
    - "max_cell_volt"
    - "min_cell_volt"
    - "max_temp"
    - "min_temp"
    - "temperature_c"
    - "relative_humidity"
    - "visibility_km"
    - "wind_speed_ms"

model_training:
  optimizer: "adam"
  learning_rate: 0.001
  dropout: 0.1
  epochs: 108
  loss: "mae"
  batch_size: 32
  validation_split: 0.15    # 验证集比例
  test_split: 0.15          # 测试集比例 (剩余为训练集)